// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAydbvJlcdbvSgEl0IQoqc4oNc7syfue_c',
    appId: '1:955828888955:web:9351bff6b36336f04249de',
    messagingSenderId: '955828888955',
    projectId: 'gasleakagemonitor-314f5',
    authDomain: 'gasleakagemonitor-314f5.firebaseapp.com',
    databaseURL: 'https://gasleakagemonitor-314f5-default-rtdb.firebaseio.com',
    storageBucket: 'gasleakagemonitor-314f5.firebasestorage.app',
    measurementId: 'G-3J9L03TFYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWd5Xf_-bHAa764RZjPY0cWRLVQnInUcg',
    appId: '1:955828888955:android:aa203bb2121759d34249de',
    messagingSenderId: '955828888955',
    projectId: 'gasleakagemonitor-314f5',
    databaseURL: 'https://gasleakagemonitor-314f5-default-rtdb.firebaseio.com',
    storageBucket: 'gasleakagemonitor-314f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAinkYEdXJqEhTILk5BGIHFXM2lLWmwruE',
    appId: '1:955828888955:ios:4bbc14ddb754ddc44249de',
    messagingSenderId: '955828888955',
    projectId: 'gasleakagemonitor-314f5',
    databaseURL: 'https://gasleakagemonitor-314f5-default-rtdb.firebaseio.com',
    storageBucket: 'gasleakagemonitor-314f5.firebasestorage.app',
    iosBundleId: 'com.example.gascheckerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAinkYEdXJqEhTILk5BGIHFXM2lLWmwruE',
    appId: '1:955828888955:ios:4bbc14ddb754ddc44249de',
    messagingSenderId: '955828888955',
    projectId: 'gasleakagemonitor-314f5',
    databaseURL: 'https://gasleakagemonitor-314f5-default-rtdb.firebaseio.com',
    storageBucket: 'gasleakagemonitor-314f5.firebasestorage.app',
    iosBundleId: 'com.example.gascheckerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAydbvJlcdbvSgEl0IQoqc4oNc7syfue_c',
    appId: '1:955828888955:web:abe761ca491808cd4249de',
    messagingSenderId: '955828888955',
    projectId: 'gasleakagemonitor-314f5',
    authDomain: 'gasleakagemonitor-314f5.firebaseapp.com',
    databaseURL: 'https://gasleakagemonitor-314f5-default-rtdb.firebaseio.com',
    storageBucket: 'gasleakagemonitor-314f5.firebasestorage.app',
    measurementId: 'G-R7HW4QE8BH',
  );
}
